//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRole
    {
        public MasterRole()
        {
            this.JuncRolePages = new HashSet<JuncRolePage>();
            this.JuncUserRoles = new HashSet<JuncUserRole>();
            this.MasterPages = new HashSet<MasterPage>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<JuncRolePage> JuncRolePages { get; set; }
        public virtual ICollection<JuncUserRole> JuncUserRoles { get; set; }
        public virtual ICollection<MasterPage> MasterPages { get; set; }
    }
}
