//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodMenguru
    {
        public PeriodMenguru()
        {
            this.BudgetMengurus = new HashSet<BudgetMenguru>();
            this.BudgetProjeks = new HashSet<BudgetProjek>();
        }
    
        public int PeriodMengurusID { get; set; }
        public int FieldMengurusID { get; set; }
        public int MengurusYear { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTimeStamp { get; set; }
    
        public virtual ICollection<BudgetMenguru> BudgetMengurus { get; set; }
        public virtual FieldMenguru FieldMenguru { get; set; }
        public virtual ICollection<BudgetProjek> BudgetProjeks { get; set; }
    }
}
